
# Site settings
# 站点名字，也就是html的title 会显示在浏览器标签上。
title: 李政宵
#name: 李政宵
# 站点副标题，会显示在首页上，可以不填。
subtitle: 
# 站点描述，可以不填
description: 

# Sidebar settings
#sidebar: true # 是否开启侧边栏.

# SNS settings 展示你的其他社交平台
#RSS: false
#github_username:    stamax360

#baseurl: ""
#url: "https://stamax360.github.io"
#github_username:  stamax360
#disqus_baseurl: "https://stamax360.github.io/"
#disqus_shortname: https://stamax360.github.io
#permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true







# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag




